### PR TITLE
SAMImprovedStreaming 1.1

### PR DESCRIPTION
**Pull request by XMDS**
1. Fix the incompatibility with the FLA plug-in, causing the game to crash
2. Now fully loaded with AML.  Removed cleo library loading.
3. Shared source with better android plugin (private sdk.)

Now they should be more stable.

### CODE REVIEW

**Comment by XMDS** [comment]
@JuniorDjjr  
SA09 has published my plugin（SAMImprovedStreaming） on AML discord.  You can add it to the mobile SA section of the mixmod, it's been tested a lot and now it works great.  I think you can add more GTA Mobile addons to mixmods to promote usage.

**Comment by JuniorDjjr** [comment]
@XMDS Hm, I looked there and didn't find.

**Comment by XMDS** [comment]
@JuniorDjjr  In AML's "roles" channel, click "all-games", you can see the .so plugin published here

**Comment by JuniorDjjr** [comment]
So is it mandatory to load the whole map? (Range1) This is horrible, not even for PC this is recommended, for mobile it would be even worse, and in the readme it even says that if you add new objects it is necessary to make them load. Does not make sense.  
And because it doesn't support "Disable CINFO.BIN and MINFO.BIN loading" it seems limiting.  
Also, you shouldn't have removed my name and put yours in the .ini file.

**Comment by XMDS** [comment]
> So is it mandatory to load the whole map? (Range1) This is horrible, not even for PC this is recommended, for mobile it would be even worse, and in the readme it even says that if you add new objects it is necessary to make them load. Does not make sense. And because it doesn't support "Disable CINFO.BIN and MINFO.BIN loading" it seems limiting. Also, you shouldn't have removed my name and put yours in the .ini file.

Essentially, even with all maps loaded in the game, it has been tested to run without issues (and even rarely affect framerates).  Of course, they can also be turned off.  It's up to the player, or if someone adds a new ini file, (maybe you're right, the default ini should be lighter).  The game crashes I get the most come from compatibility with other plugins.  For disabling .bin files, it just disables the PreLoadLODs option.  Because when you reload the lod, the game doesn't write new data to the .bin file, causing the crash.  So I did a test.  (I think it will be solved later) Finally, about the ini, I started testing with a new ini file and at the end I copied your original ini options, but I didn't copy the top two lines, I forgot, if you want to add  your name, you can do it.  Also has your name elsewhere in the plugin (source code log file)

**Comment by JuniorDjjr** [comment]
But why?
> If you install some new map mods, this plugin may cause the game to crash, please set the model ID range for loading new map mods in the ini file

**Pull request merged**
